[package]
name = "hpl-schema"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true

[dependencies]
cosmwasm-std.workspace = true
cosmwasm-schema.workspace = true

hpl-interface.workspace = true
