name: Build and Publish WebAssembly

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build WebAssembly
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-

      - name: Install Dependencies and Build WebAssembly
        run: |
          make install-prod
          cargo generate-lockfile
          make ci-build

      - name: Publish artifacts
        uses: gavv/pull-request-artifacts@v3
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-branch: artifacts
          artifacts: |
            wasm_codes.zip
